kind: Service
apiVersion: v1
metadata:
  labels:
{{ include "REPLACE_ME_APP_NAME.labels.stakater" . | indent 4 }}
{{ include "REPLACE_ME_APP_NAME.labels.chart" . | indent 4 }}
    k8sapp: maven-app   # label used by servicemonitor to monitor this service
  name: {{ template "REPLACE_ME_APP_NAME.name" . }}
spec:
  selector:
{{ toYaml .Values.deployment.podLabels | indent 4 }}
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
