apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  # `generateName` will use the value as a prefix and generate unique name adding a random suffix at runtime
  generateName: REPLACE_ME_APP_NAME-pipeline-
  name: REPLACE_ME_APP_NAME-pipeline
spec:
  pipelineRef:
    name: pipeline-maven
  timeout: "0h5m30s"
  serviceAccountName: "stakater-tekton-builder"
  resources:
    - name: app-git
      resourceSpec:
        type: git
        params:
        - name: revision
          value: master
        - name: url
          value: REPLACE_ME_GIT_REPOSITORY_URL
    - name: app-image
      resourceRef:
        name: REPLACE_ME_APP_NAME-image