#!/usr/bin/env groovy
@Library('github.com/stakater/stakater-pipeline-library@v2.16.1') _

releaseApplication {
    appName = "REPLACE_ME_APP_NAME"
    appType = "dotnet"
    builderImage = "stakater/builder-dotnet:2.2-centos7"
    goal = "restore;publish -c Release -o out"
    notifySlack = false
    runIntegrationTest = false
    gitUser = "REPLACE_ME_GIT_USER"
    gitEmail = "REPLACE_ME_GIT_MAIL"
    usePersonalAccessToken = true
    tokenCredentialID = 'REPLACE_ME_TOKEN_CREDENTIALS_ID'
    serviceAccount = "REPLACE_ME_APP_NAME"
    dockerRepositoryURL = 'REPLACE_ME_DOCKER_REPOSITORY'
    chartRepositoryURL = 'REPLACE_ME_CHART_REPOSITORY_URL'
}