#!/usr/bin/env groovy
// TODO; Have to change this to master, once that branch gets merged
@Library('github.com/stakater/fabric8-pipeline-library@add-e2e-teststage') _

appWithDockerfileBuildRelease {
    dockerRegistryURL = "docker.io"
}