apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "<app_name>.labels.stakater" . | indent 4 }}
{{ include "<app_name>.labels.chart" . | indent 4 }}
  name: {{ template "<app_name>.name" . }}
spec:
  replicas: {{ .Values.appname.deployment.replicas }}
  template:
    metadata:
      labels:
{{ toYaml .Values.appname.deployment.podLabels | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.appname.deployment.container.name }}
        image: {{ .Values.appname.deployment.container.image | quote }}
        ports:
        - containerPort: 8080