apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: REPLACE_ME_APP_NAME
  labels:     
    provider: stakater
    version: "1.0.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
      # This label is used by Service to connect to pod, 
      # If you change it, so change Service's labelSelector as well.
        app: maven-app    
    spec:
      containers:
      - name: REPLACE_ME_APP_NAME
        image: "REPLACE_ME_APP_IMAGE"
        ports:
        - containerPort: 8080