#!/usr/bin/env groovy
@Library('github.com/stakater/fabric8-pipeline-library@v2.10.3') _

releaseMavenApplication {
    gitUser = "REPLACE_ME_GIT_USER"
    gitEmail = "REPLACE_ME_GIT_MAIL"
    appName = "REPLACE_ME_APP_NAME"    
    deployUsingMakeTarget = true    
    dockerRepositoryURL = 'DOCKER_REPOSITORY'
    chartRepositoryURL = 'CHART_REPOSITORY_URL'
    javaRepositoryURL = 'NEXUS_REPOSITORY_URL/repository/maven'
}
