apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "REPLACE_ME_APP_NAME.labels.stakater" . | indent 4 }}
{{ include "REPLACE_ME_APP_NAME.labels.chart" . | indent 4 }}
  name: {{ template "REPLACE_ME_APP_NAME.name" . }}